[config]
# ...
#
[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.hyprland]
input_path = 'templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = 'templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.wofi]
input_path = 'templates/colors.css'
output_path = '~/.config/wofi/colors.css'

[templates.pywalfox]
input_path = 'templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.kitty]
input_path = "templates/kitty-colors.conf"
output_path = "~/.config/kitty/themes/matugen.conf"
post_hook = "kitty +kitten themes --reload-in=all matugen"
[templates.gtk3]
input_path = 'templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = 'templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.vesktop]
input_path = 'templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.dunst]
input_path = 'templates/dunstrc-colors'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'killall -SIGUSR2 dunst'
[templates.ytmusic]
input_path = 'templates/colors.css'
output_path = '~/.config/yt-music/colors.css'
